package net.uiqui.embedhttp.api;

/**
 * Interface representing an HTTP request handler.
 * Implementations of this interface define how to handle HTTP requests.
 */
@FunctionalInterface
public interface HttpRequestHandler {
    /**
     * Handles an HTTP request and returns an HTTP response.
     *
     * @param request the HTTP request to handle
     * @return the HTTP response generated by handling the request
     */
    HttpResponse handle(HttpRequest request);
}
