name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Give execute permission to gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew test

    - name: jacoco-summary
      uses: jjmrocha/jacoco-summary@v1.1.0
